### ISSUE TITLE
Not working with `Jest` from v3.0.0

### ISSUE THREAD

**Issue by svitovyda** [redux-utilities/redux-actions#399]
When upgrading to `3.0.0`, `Jest`is unable to find the redux-actions package:

```
● Test suite failed to run

    Cannot find module 'redux-actions' from '.../XXX.ts'

    Require stack:
    ...
    > 1 | import { handleActions } from 'redux-actions';
```

My project is built by `webpack`, so I cannot migrate it to `ESM`, but everything else works with v3 - `typescript` compilation, `webpack` dev server runs perfectly working application and `webpack build` runs without any errors.

_Addition information:_
The dependency is added together with `@types/redux-actions`, it is included in each package's `package.json`, but I also added it to the root one, from where the tests are run
```
Node v16
npm v8
yarn v1
```

**Comment by u3ih** [comment]
is there any update? i'm experiencing the same issue
